{
 "title": "Artemis Sample Dashboard 2",
 "tags": [ "artemis" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue Message Counts",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artemis_message_count ",
     "legendFormat": "Total ({{broker}} - {{address}}::{{queue}})"
    },
    {
     "expr": "artemis_delivering_message_count ",
     "legendFormat": "Delivering ({{broker}} - {{address}}::{{queue}})"
    },
    {
     "expr": "artemis_scheduled_message_count ",
     "legendFormat": "Scheduled ({{broker}} - {{address}}::{{queue}})"
    }
   ]
  },
  {
   "title": "Messages Added & Acked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artemis_messages_acknowledged",
     "legendFormat": "Acked ({{broker}} - {{address}}::{{queue}})"
    },
    {
     "expr": "artemis_messages_added",
     "legendFormat": "Added ({{broker}} - {{address}}::{{queue}})"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "graph",
   "description": "Number of clients currently connected to this server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "artemis_connection_count", "legendFormat": "{{broker}}" }
   ]
  },
  {
   "title": "Queue Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_delivering_persistent_size",
     "legendFormat": "Delivering ({{broker}} - {{address}}::{{queue}})"
    },
    {
     "expr": "artemis_persistent_size",
     "legendFormat": "Total ({{broker}} - {{address}}::{{queue}})"
    },
    {
     "expr": "artemis_scheduled_persistent_size",
     "legendFormat": "Scheduled ({{broker}} - {{address}}::{{queue}})"
    }
   ]
  },
  {
   "title": "Address Message Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artemis_unrouted_message_count",
     "legendFormat": "Unrouted ({{broker}} - {{address}})"
    },
    {
     "expr": "artemis_routed_message_count",
     "legendFormat": "Routed ({{broker}} - {{address}})"
    }
   ]
  },
  {
   "title": "Address Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "artemis_address_memory_usage", "legendFormat": "{{broker}}" }
   ]
  },
  {
   "title": "Consumer Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "artemis_consumer_count",
     "legendFormat": "{{broker}} - {{address}}::{{queue}}"
    }
   ]
  }
 ]
}